// AUTO-GENERATED by build-data.js from the PopTracker pack. Do not edit by hand.
window.TRACKER_DATA = {
  "keyItems": [
    [
      {
        "code": "1st_Tablet",
        "name": "1st Tablet",
        "img": "images/items/tablet1_alt.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Pyramid_Page",
        "name": "Pyramid Page",
        "img": "images/items/pyramid_page2.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Walse_Tower_Key",
        "name": "Walse Tower Key",
        "img": "images/items/walse_key2.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Ifrit's_Fire",
        "name": "Ifrit's Fire",
        "img": "images/items/fire.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Moogle_Suit",
        "name": "Moogle Suit",
        "img": "images/items/moogle.png",
        "off": "images/items/w2_keys_disabled.png"
      }
    ],
    [
      {
        "code": "2nd_Tablet",
        "name": "2nd Tablet",
        "img": "images/items/tablet2_alt.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Shrine_Page",
        "name": "Shrine Page",
        "img": "images/items/shrine_page2.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Steamship_Key",
        "name": "Steamship Key",
        "img": "images/items/steamship_key2.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "SandwormBait",
        "name": "Sandworm Bait",
        "img": "images/items/bait.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Mirage_Radar",
        "name": "Mirage Radar",
        "img": "images/items/mirage_radar.png",
        "off": "images/items/w2_keys_disabled.png"
      }
    ],
    [
      {
        "code": "3rd_Tablet",
        "name": "3rd Tablet",
        "img": "images/items/tablet3_alt.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Trench_Page",
        "name": "Trench Page",
        "img": "images/items/trench_page2.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Submarine_Key",
        "name": "Submarine Key",
        "img": "images/items/sub_key2.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Hiryuu_Call",
        "name": "Hiryuu Call",
        "img": "images/items/hiryuu.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Adamantite",
        "name": "Adamantite",
        "img": "images/items/adamantite.png",
        "off": "images/items/w2_keys_disabled.png"
      }
    ],
    [
      {
        "code": "4th_Tablet",
        "name": "4th Tablet",
        "img": "images/items/tablet4_alt.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Falls_Page",
        "name": "Falls Page",
        "img": "images/items/falls_page2.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Big_Bridge_Key",
        "name": "Big Bridge Key",
        "img": "images/items/bridge_key2.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "Elder_Branch",
        "name": "Elder Branch",
        "img": "images/items/branch.png",
        "off": "images/items/w2_keys_disabled.png"
      },
      {
        "code": "W2_Keys",
        "name": "W2 Keys (Anti-Barrier + Bracelet)",
        "img": "images/items/w2_keys.png",
        "off": "images/items/w2_keys_disabled.png"
      }
    ]
  ],
  "bosses": [
    [
      {
        "code": "wingraptorx",
        "name": "Wingraptor",
        "img": "images/bosses/wingraptor.png"
      },
      {
        "code": "karlibosx",
        "name": "Karlibos",
        "img": "images/bosses/karlibos.png"
      },
      {
        "code": "sirenx",
        "name": "Siren",
        "img": "images/bosses/siren.png"
      },
      {
        "code": "magisax",
        "name": "Magisa",
        "img": "images/bosses/magisa.png"
      },
      {
        "code": "galurax",
        "name": "Galura",
        "img": "images/bosses/galura.png"
      },
      {
        "code": "shivax",
        "name": "Shiva",
        "img": "images/bosses/shiva.png"
      },
      {
        "code": "liquidflamex",
        "name": "Liquidflame",
        "img": "images/bosses/liquidflame_alt.png"
      }
    ],
    [
      {
        "code": "ironclawx",
        "name": "Ironclaw",
        "img": "images/bosses/ironclaw.png"
      },
      {
        "code": "ifritx",
        "name": "Ifrit",
        "img": "images/bosses/ifrit.png"
      },
      {
        "code": "byblosx",
        "name": "Byblos",
        "img": "images/bosses/byblos.png"
      },
      {
        "code": "sandwormx",
        "name": "Sandworm",
        "img": "images/bosses/sandworm.png"
      },
      {
        "code": "adamantx",
        "name": "Adamant",
        "img": "images/bosses/adamant.png"
      },
      {
        "code": "solcannonx",
        "name": "Solcannon",
        "img": "images/bosses/solcannon.png"
      },
      {
        "code": "archaeavisx",
        "name": "Archaeavis",
        "img": "images/bosses/archaeavis.png"
      }
    ],
    [
      {
        "code": "crayclawx",
        "name": "Crayclaw",
        "img": "images/bosses/crayclaw.png"
      },
      {
        "code": "chimbrainx",
        "name": "Chimbrain",
        "img": "images/bosses/chimbrain.png"
      },
      {
        "code": "titanx",
        "name": "Titan",
        "img": "images/bosses/titan.png"
      },
      {
        "code": "puroborosx",
        "name": "Puroboros",
        "img": "images/bosses/puroboros.png"
      },
      {
        "code": "tyrasaurusx",
        "name": "Tyrasaurus",
        "img": "images/bosses/tyrasaurus_alt.png"
      },
      {
        "code": "abductorx",
        "name": "Abductor",
        "img": "images/bosses/abductor.png"
      },
      {
        "code": "hiryuuplantx",
        "name": "Hiryuuplant",
        "img": "images/bosses/hiryuuplant_alt.png"
      }
    ],
    [
      {
        "code": "guardianx",
        "name": "Guardian",
        "img": "images/bosses/guardian_alt.png"
      },
      {
        "code": "atomosx",
        "name": "Atomos",
        "img": "images/bosses/atomos.png"
      },
      {
        "code": "carbunklex",
        "name": "Carbunkle",
        "img": "images/bosses/carbunkle.png"
      },
      {
        "code": "gilga1x",
        "name": "Gilga 1",
        "img": "images/bosses/gilga1_alt.png"
      },
      {
        "code": "gilga2x",
        "name": "Gilga 2",
        "img": "images/bosses/gilga2_alt.png"
      },
      {
        "code": "gilgaenkix",
        "name": "Gilgaenki",
        "img": "images/bosses/gilgaenki_alt.png"
      },
      {
        "code": "gilga4x",
        "name": "Gilga 4",
        "img": "images/bosses/gilga4_alt.png"
      }
    ],
    [
      {
        "code": "antlionx",
        "name": "Antlion",
        "img": "images/bosses/antlion.png"
      },
      {
        "code": "gargoylex",
        "name": "Gargoyle",
        "img": "images/bosses/gargoyle.png"
      },
      {
        "code": "merugenex",
        "name": "Merugene",
        "img": "images/bosses/merugene.png"
      },
      {
        "code": "stalkerx",
        "name": "Stalker",
        "img": "images/bosses/stalker.png"
      },
      {
        "code": "leviathanx",
        "name": "Leviathan",
        "img": "images/bosses/leviathan.png"
      },
      {
        "code": "tritonx",
        "name": "Triton",
        "img": "images/bosses/triton.png"
      },
      {
        "code": "omniscientx",
        "name": "Omniscient",
        "img": "images/bosses/omniscient.png"
      }
    ],
    [
      {
        "code": "minotaurusx",
        "name": "Minotaurus",
        "img": "images/bosses/minotaurus.png"
      },
      {
        "code": "gogox",
        "name": "Gogo",
        "img": "images/bosses/gogo.png"
      },
      {
        "code": "odinx",
        "name": "Odin",
        "img": "images/bosses/odin.png"
      },
      {
        "code": "bahamutx",
        "name": "Bahamut",
        "img": "images/bosses/bahamut.png"
      },
      {
        "code": "ramuhx",
        "name": "Ramuh",
        "img": "images/bosses/ramuh.png"
      },
      {
        "code": "shoatx",
        "name": "Shoat",
        "img": "images/bosses/shoat.png"
      },
      {
        "code": "golemx",
        "name": "Golem",
        "img": "images/bosses/golem.png"
      }
    ],
    [
      {
        "code": "calofisterix",
        "name": "Calofisteri",
        "img": "images/bosses/calofisteri.png"
      },
      {
        "code": "apandax",
        "name": "Apanda",
        "img": "images/bosses/apanda.png"
      },
      {
        "code": "apocalypsex",
        "name": "Apocalypse",
        "img": "images/bosses/apocalypse.png"
      },
      {
        "code": "catastrophx",
        "name": "Catastroph",
        "img": "images/bosses/catastroph.png"
      },
      {
        "code": "halicarnasox",
        "name": "Halicarnaso",
        "img": "images/bosses/halicarnaso.png"
      },
      {
        "code": "twintaniax",
        "name": "Twintania",
        "img": "images/bosses/twintania.png"
      },
      {
        "code": "necrophobex",
        "name": "Necrophobe",
        "img": "images/bosses/necrophobe.png"
      }
    ]
  ],
  "jobs": [
    [
      {
        "code": "Knight_Crystal",
        "name": "Knight Crystal",
        "img": "images/jobs/knight_job.png"
      },
      {
        "code": "Monk_Crystal",
        "name": "Monk Crystal",
        "img": "images/jobs/monk_job.png"
      },
      {
        "code": "Thief_Crystal",
        "name": "Thief Crystal",
        "img": "images/jobs/thief_job.png"
      },
      {
        "code": "Dragoon_Crystal",
        "name": "Dragoon Crystal",
        "img": "images/jobs/dragoon_job.png"
      },
      {
        "code": "Ninja_Crystal",
        "name": "Ninja Crystal",
        "img": "images/jobs/ninja_job.png"
      }
    ],
    [
      {
        "code": "Samurai_Crystal",
        "name": "Samurai Crystal",
        "img": "images/jobs/samurai_job.png"
      },
      {
        "code": "Berserker_Crystal",
        "name": "Berserker Crystal",
        "img": "images/jobs/berserker_job.png"
      },
      {
        "code": "Hunter_Crystal",
        "name": "Hunter Crystal",
        "img": "images/jobs/hunter_job.png"
      },
      {
        "code": "MysticKnight_Crystal",
        "name": "Mystic Knight Crystal",
        "img": "images/jobs/mystic_knight_job.png"
      },
      {
        "code": "WhiteMage_Crystal",
        "name": "White Mage Crystal",
        "img": "images/jobs/white_mage_job.png"
      }
    ],
    [
      {
        "code": "BlackMage_Crystal",
        "name": "Black Mage Crystal",
        "img": "images/jobs/black_mage_job.png"
      },
      {
        "code": "TimeMage_Crystal",
        "name": "Time Mage Crystal",
        "img": "images/jobs/time_mage_job.png"
      },
      {
        "code": "Summoner_Crystal",
        "name": "Summoner Crystal",
        "img": "images/jobs/summoner_job.png"
      },
      {
        "code": "BlueMage_Crystal",
        "name": "Blue Mage Crystal",
        "img": "images/jobs/blue_mage_job.png"
      },
      {
        "code": "RedMage_Crystal",
        "name": "Red Mage Crystal",
        "img": "images/jobs/red_mage_job.png"
      }
    ],
    [
      {
        "code": "Trainer_Crystal",
        "name": "Trainer Crystal",
        "img": "images/jobs/trainer_job.png"
      },
      {
        "code": "Chemist_Crystal",
        "name": "Chemist Crystal",
        "img": "images/jobs/chemist_job.png"
      },
      {
        "code": "Geomancer_Crystal",
        "name": "Geomancer Crystal",
        "img": "images/jobs/geomancer_job.png"
      },
      {
        "code": "Bard_Crystal",
        "name": "Bard Crystal",
        "img": "images/jobs/bard_job.png"
      },
      {
        "code": "Dancer_Crystal",
        "name": "Dancer Crystal",
        "img": "images/jobs/dancer_job.png"
      }
    ],
    [
      {
        "code": "Mimic_Crystal",
        "name": "Mimic Crystal",
        "img": "images/jobs/mimic_job.png"
      },
      {
        "code": "Freelancer_Crystal",
        "name": "Freelancer Crystal",
        "img": "images/jobs/freelancer_job.png"
      }
    ]
  ],
  "events": [
    {
      "code": "piano_counter",
      "name": "Pianos",
      "img": "images/icons/piano.png",
      "type": "counter",
      "max": 8
    },
    {
      "code": "exdeathw2",
      "name": "ExDeath (W2)",
      "img": "images/bosses/exdeath.png",
      "type": "toggle"
    },
    {
      "code": "exdeath",
      "name": "Neo ExDeath",
      "img": "images/bosses/neo_exdeath.png",
      "type": "toggle"
    }
  ]
};
